language: ruby
cache: bundler
rvm:
  - 2.5
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
notifications:
  email: never
